import { createContext, useContext, useState, ReactNode } from "react";
import { settingsAndHelpTranslations } from "@/data/settingsHelpTranslations";

export type Language = "en" | "hi" | "te";

const translations = {
  en: {
    // Top bar
    online: "Online",
    offline: "Offline",
    notifications: "Notifications",
    noNotifications: "No new notifications",
    
    // Bottom nav
    home: "Home",
    categories: "Categories",
    earnings: "Earnings",
    account: "Account",
    
    // Home
    goOnline: "Go Online",
    goOffline: "Go Offline",
    loadingMap: "Loading map...",
    completeAppToGoOnline: "Please log in and complete your application to go online.",
    
    // Categories
    farmWorker: "Farm Worker",
    farmWorkerSub: "Find Labor Jobs",
    rentVehicle: "Rent Vehicle",
    rentVehicleSub: "Hire Cars & Bikes",
    agrizinDriver: "Agrizin Driver",
    agrizinDriverSub: "Agricultural Transport",
    completed: "Completed",
    inProgress: "In Progress",
    notAdded: "Not added",
    
    // Account
    myApplications: "📋 My Applications",
    editDetails: "Edit Details",
    addFarmWorkerDetails: "Add Farm Worker Details",
    addRentVehicleDetails: "Add Rent Vehicle Details",
    addAgrizinDriverDetails: "Add Agrizin Driver Details",
    referPartner: "Refer Agrizin Partner",
    referSubtitle: "Invite and earn rewards",
    appSettings: "App Settings",
    appSettingsSub: "Language, notifications",
    logout: "Logout",
    welcomeAgrizin: "Welcome to Agrizin",
    login: "Login",
    loginToView: "Login to view your earnings",
    name: "Name",
    enterName: "Enter your name",
    phoneNumber: "Phone Number",
    otpSentTo: "OTP sent to",
    enterOtp: "Enter OTP",
    enterOtpPlaceholder: "Enter 4-digit OTP",
    verifyOtp: "Verify OTP",
    verifying: "Verifying...",
    changeDetails: "← Change details",
    back: "Back",
    
    // Earnings
    totalEarnings: "Total Earnings",
    thisWeek: "This Week",
    thisMonth: "This Month",
    dailyEarnings: "Daily Earnings",
    today: "Today:",
    trips: "Trips",
    paymentHistory: "Payment History",
    getStartedEarnings: "Get started with your earnings",
    getStartedEarningsDesc: "Complete a service registration to start tracking your earnings here.",
    availableBalance: "Available Balance",
    withdrawn: "Withdrawn",
    pendingWithdrawalAmount: "Pending",
    withdrawMoney: "Withdraw Money",
    upiId: "UPI ID",
    amount: "Amount",
    minimum: "Minimum",
    confirmWithdrawal: "Confirm Withdrawal",
    processing: "Processing...",
    withdrawalRequested: "Withdrawal request submitted!",
    enterUpiId: "Please enter your UPI ID",
    minWithdrawal: "Minimum withdrawal is ₹50",
    insufficientBalance: "Insufficient balance",
    referralEarnings: "Referral Earnings",
    totalReferrals: "Total Referrals",
    noReferralsYet: "No referrals yet. Share your code to earn!",
    noWithdrawalsYet: "No withdrawals yet",
    withdrawalHistory: "Withdrawal History",
    yourReferralCode: "Your Referral Code",
    shareReferral: "Share Referral",
    referralShareText: "Join Agrizin Partner app and earn! Use my referral code:",
    copiedToClipboard: "Copied to clipboard!",
    perReferral: "per referral",
    
    // Detail labels
    nameLabel: "Name",
    skills: "Skills",
    experience: "Experience",
    location: "Location",
    availability: "Availability",
    vehicle: "Vehicle",
    license: "License",
    registration: "Registration",
    years: "years",
    
    // Timeline
    submitted: "Submitted",
    
    // Language
    selectLanguage: "Select Language",
    english: "English",
    hindi: "हिन्दी",
    telugu: "తెలుగు",

    // Navbar desktop
    myEarnings: "My Earnings",
    
    // Settings
    language: "Language",
    notificationsToggle: "Notifications",
    comingSoon: "Coming soon!",

    // Edit form
    save: "Save Changes",
    saving: "Saving...",
    cancel: "Cancel",
    updateSuccess: "Details updated successfully!",
    updateError: "Failed to update. Please try again.",
    state: "State",
    district: "District",
    mandal: "Mandal",
    village: "Village",
    expectedWage: "Expected Wage",
    wageType: "Wage Type",
    perDay: "Per Day",
    perMonth: "Per Month",
    perHour: "Per Hour",
    experienceYears: "Experience (Years)",
    fullName: "Full Name",
    mobile: "Mobile",
    vehicleNumber: "Vehicle Number",
    vehicleUsageType: "Vehicle Usage Type",
    drivingLicense: "Driving License No.",
    vehicleMake: "Vehicle Make",
    vehicleModel: "Vehicle Model",
    registrationNo: "Registration No.",

    // Registration - common
    loading: "Loading...",
    duplicateSubmission: "Duplicate Submission",
    alreadySubmittedApp: "You have already submitted your application.",
    alreadySubmittedDriver: "You have already submitted your Agrizin Driver application.",
    alreadyRegistered: "Already Registered",
    alreadyRegisteredFarm: "You have already submitted a farm worker application. You cannot create another one.",
    goToDashboard: "Go to Dashboard",
    vehicleRegistration: "Vehicle Registration",
    farmWorkerTitle: "Farm Worker",
    agrizinDriverTitle: "Agrizin Driver",
    step1Personal: "Step 1: Personal Details",
    step2Vehicle: "Step 2: Vehicle Details",
    step2VehiclePref: "Step 2: Vehicle & Preferences",
    personalDetails: "Personal Details",
    address: "Address",
    addressDetails: "Address Details",
    upload: "Upload",
    change: "Change",
    uploadImage: "Upload Image",
    uploadRcImage: "Upload RC Image",
    uploadRcOptional: "Upload RC Document (Optional)",
    uploadVehiclePhotos: "Upload Vehicle Photos",
    uploadDrivingLicense: "Upload Driving License",
    uploadAadhaarPan: "Aadhaar / PAN Images *",
    frontSide: "Front Side",
    backSide: "Back Side",
    frontImage: "Front Image",
    backImage: "Back Image",
    addPhoto: "Add Photo",
    nameRequired: "Full Name *",
    egJohn: "E.g. John Doe",
    age: "Age",
    eg25: "E.g. 25",
    gender: "Gender",
    selectGender: "Select Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    mobileRequired: "Mobile Number *",
    egMobile: "E.g. 9876543210",
    aadhaarPanLabel: "Aadhaar / PAN Number *",
    egAadhaar: "E.g. 123456789012 or ABCDE1234F",
    country: "Country",
    india: "India",
    selectStateReq: "Select State *",
    districtReq: "District *",
    selectMandal: "Mandal",
    enterVillage: "Enter Village Name",
    villagePh: "Village",
    next: "Next →",
    submit: "Submit Application",
    submitting: "Submitting...",
    backToStep1: "← Back to Step 1",
    vehicleType: "Vehicle Type",
    vehicleTypeReq: "Vehicle Type *",
    selectVehicleType: "Select Vehicle Type",
    canSelectMultiple: "You can select one or more vehicle types",
    vehicleNumberReq: "Vehicle Number *",
    egVehicleNum: "E.g. MH01AB1234",
    drivingLicenseReq: "Driving License Number *",
    egDl: "E.g. DL1234567890123",
    workDuration: "Work Duration *",
    selectDuration: "Select Duration",
    preferredLocation: "Preferred Location *",
    egPreferredLoc: "E.g. Hyderabad, Warangal, Guntur",
    driverPreferences: "Driver Preferences",
    vehicleDetails: "Vehicle Details",
    categoryReq: "Category *",
    selectCategory: "Select category",
    single: "Single",
    group: "Group",
    workersCount: "Number of Workers *",
    enterWorkers: "Enter number of workers",
    skillsWorkType: "Skills & Work Type *",
    selectWorkTypes: "Select work types...",
    selected: "selected",
    experienceReq: "Experience *",
    selectExperience: "Select experience",
    exp01: "0–1 years",
    exp13: "1–3 years",
    exp35: "3–5 years",
    exp5: "5+ years",
    availabilityReq: "Availability *",
    fullTime: "Full-time",
    partTime: "Part-time",
    daily: "Daily",
    seasonal: "Seasonal",
    expectedWageLabel: "Expected Wage",
    perDayShort: "/ per day",
    perHourShort: "/ per hour",
    perMonthShort: "/ per month",
    useCurrentLocation: "Use my current location (recommended)",
    gettingLocation: "Getting location…",
    gpsCaptured: "GPS captured",
    gpsHelp: "Helps farmers find you in \"Nearby\" search on agrizin.com",
    fillRequired: "Please fill all required fields",
    thankYou: "Thank You!",
    thankYouBody: "Thank you for choosing Agrizin Partner. Your application has been successfully submitted. Our team will contact you shortly for verification.",
    ok: "OK",
    ...settingsAndHelpTranslations.en,
  },
  hi: {
    online: "ऑनलाइन",
    offline: "ऑफ़लाइन",
    notifications: "सूचनाएं",
    noNotifications: "कोई नई सूचना नहीं",
    
    home: "होम",
    categories: "श्रेणियाँ",
    earnings: "कमाई",
    account: "खाता",
    
    goOnline: "ऑनलाइन जाएं",
    goOffline: "ऑफ़लाइन जाएं",
    loadingMap: "मानचित्र लोड हो रहा है...",
    completeAppToGoOnline: "कृपया लॉग इन करें और ऑनलाइन जाने के लिए अपना आवेदन पूरा करें।",
    
    farmWorker: "खेत मजदूर",
    farmWorkerSub: "मजदूरी के काम खोजें",
    rentVehicle: "वाहन किराया",
    rentVehicleSub: "कार और बाइक किराये पर लें",
    agrizinDriver: "एग्रिज़िन ड्राइवर",
    agrizinDriverSub: "कृषि परिवहन",
    completed: "पूर्ण",
    inProgress: "प्रगति में",
    notAdded: "जोड़ा नहीं गया",
    
    myApplications: "📋 मेरे आवेदन",
    editDetails: "विवरण संपादित करें",
    addFarmWorkerDetails: "खेत मजदूर विवरण जोड़ें",
    addRentVehicleDetails: "वाहन किराया विवरण जोड़ें",
    addAgrizinDriverDetails: "एग्रिज़िन ड्राइवर विवरण जोड़ें",
    referPartner: "एग्रिज़िन पार्टनर रेफर करें",
    referSubtitle: "आमंत्रित करें और पुरस्कार कमाएं",
    appSettings: "ऐप सेटिंग्स",
    appSettingsSub: "भाषा, सूचनाएं",
    logout: "लॉगआउट",
    welcomeAgrizin: "एग्रिज़िन में आपका स्वागत है",
    login: "लॉगिन",
    loginToView: "अपनी कमाई देखने के लिए लॉगिन करें",
    name: "नाम",
    enterName: "अपना नाम दर्ज करें",
    phoneNumber: "फ़ोन नंबर",
    otpSentTo: "OTP भेजा गया",
    enterOtp: "OTP दर्ज करें",
    enterOtpPlaceholder: "4-अंकीय OTP दर्ज करें",
    verifyOtp: "OTP सत्यापित करें",
    verifying: "सत्यापित हो रहा है...",
    changeDetails: "← विवरण बदलें",
    back: "वापस",
    
    totalEarnings: "कुल कमाई",
    thisWeek: "इस सप्ताह",
    thisMonth: "इस महीने",
    dailyEarnings: "दैनिक कमाई",
    today: "आज:",
    trips: "यात्राएं",
    paymentHistory: "भुगतान इतिहास",
    getStartedEarnings: "अपनी कमाई शुरू करें",
    getStartedEarningsDesc: "यहां अपनी कमाई ट्रैक करने के लिए एक सेवा पंजीकरण पूरा करें।",
    availableBalance: "उपलब्ध शेष",
    withdrawn: "निकाला गया",
    pendingWithdrawalAmount: "लंबित",
    withdrawMoney: "पैसे निकालें",
    upiId: "UPI ID",
    amount: "राशि",
    minimum: "न्यूनतम",
    confirmWithdrawal: "निकासी की पुष्टि करें",
    processing: "प्रोसेसिंग...",
    withdrawalRequested: "निकासी अनुरोध सबमिट किया गया!",
    enterUpiId: "कृपया अपना UPI ID दर्ज करें",
    minWithdrawal: "न्यूनतम निकासी ₹50 है",
    insufficientBalance: "अपर्याप्त शेष",
    referralEarnings: "रेफरल कमाई",
    totalReferrals: "कुल रेफरल",
    noReferralsYet: "अभी तक कोई रेफरल नहीं। कमाने के लिए अपना कोड शेयर करें!",
    noWithdrawalsYet: "अभी तक कोई निकासी नहीं",
    withdrawalHistory: "निकासी इतिहास",
    yourReferralCode: "आपका रेफरल कोड",
    shareReferral: "रेफरल शेयर करें",
    referralShareText: "Agrizin Partner ऐप से जुड़ें और कमाएं! मेरा रेफरल कोड उपयोग करें:",
    copiedToClipboard: "कॉपी हो गया!",
    perReferral: "प्रति रेफरल",
    
    nameLabel: "नाम",
    skills: "कौशल",
    experience: "अनुभव",
    location: "स्थान",
    availability: "उपलब्धता",
    vehicle: "वाहन",
    license: "लाइसेंस",
    registration: "पंजीकरण",
    years: "वर्ष",
    
    submitted: "जमा किया",
    
    selectLanguage: "भाषा चुनें",
    english: "English",
    hindi: "हिन्दी",
    telugu: "తెలుగు",
    
    myEarnings: "मेरी कमाई",
    
    language: "भाषा",
    notificationsToggle: "सूचनाएं",
    comingSoon: "जल्द आ रहा है!",

    save: "बदलाव सहेजें",
    saving: "सहेज रहे हैं...",
    cancel: "रद्द करें",
    updateSuccess: "विवरण सफलतापूर्वक अपडेट किए गए!",
    updateError: "अपडेट विफल। कृपया पुनः प्रयास करें।",
    state: "राज्य",
    district: "जिला",
    mandal: "मंडल",
    village: "गांव",
    expectedWage: "अपेक्षित वेतन",
    wageType: "वेतन प्रकार",
    perDay: "प्रति दिन",
    perMonth: "प्रति माह",
    perHour: "प्रति घंटा",
    experienceYears: "अनुभव (वर्ष)",
    fullName: "पूरा नाम",
    mobile: "मोबाइल",
    vehicleNumber: "वाहन नंबर",
    vehicleUsageType: "वाहन उपयोग प्रकार",
    drivingLicense: "ड्राइविंग लाइसेंस नं.",
    vehicleMake: "वाहन कंपनी",
    vehicleModel: "वाहन मॉडल",
    registrationNo: "पंजीकरण नं.",

    loading: "लोड हो रहा है...",
    duplicateSubmission: "डुप्लिकेट सबमिशन",
    alreadySubmittedApp: "आप पहले ही अपना आवेदन जमा कर चुके हैं।",
    alreadySubmittedDriver: "आप पहले ही एग्रिज़िन ड्राइवर आवेदन जमा कर चुके हैं।",
    alreadyRegistered: "पहले से पंजीकृत",
    alreadyRegisteredFarm: "आपने पहले ही खेत मजदूर आवेदन जमा कर दिया है। दूसरा नहीं बना सकते।",
    goToDashboard: "डैशबोर्ड पर जाएं",
    vehicleRegistration: "वाहन पंजीकरण",
    farmWorkerTitle: "खेत मजदूर",
    agrizinDriverTitle: "एग्रिज़िन ड्राइवर",
    step1Personal: "चरण 1: व्यक्तिगत विवरण",
    step2Vehicle: "चरण 2: वाहन विवरण",
    step2VehiclePref: "चरण 2: वाहन और प्राथमिकताएं",
    personalDetails: "व्यक्तिगत विवरण",
    address: "पता",
    addressDetails: "पता विवरण",
    upload: "अपलोड",
    change: "बदलें",
    uploadImage: "छवि अपलोड करें",
    uploadRcImage: "RC छवि अपलोड करें",
    uploadRcOptional: "RC दस्तावेज़ अपलोड करें (वैकल्पिक)",
    uploadVehiclePhotos: "वाहन फोटो अपलोड करें",
    uploadDrivingLicense: "ड्राइविंग लाइसेंस अपलोड करें",
    uploadAadhaarPan: "आधार / पैन छवियां *",
    frontSide: "सामने का भाग",
    backSide: "पीछे का भाग",
    frontImage: "सामने की छवि",
    backImage: "पीछे की छवि",
    addPhoto: "फोटो जोड़ें",
    nameRequired: "पूरा नाम *",
    egJohn: "उदा. राजेश कुमार",
    age: "आयु",
    eg25: "उदा. 25",
    gender: "लिंग",
    selectGender: "लिंग चुनें",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    mobileRequired: "मोबाइल नंबर *",
    egMobile: "उदा. 9876543210",
    aadhaarPanLabel: "आधार / पैन नंबर *",
    egAadhaar: "उदा. 123456789012 या ABCDE1234F",
    country: "देश",
    india: "भारत",
    selectStateReq: "राज्य चुनें *",
    districtReq: "जिला *",
    selectMandal: "मंडल",
    enterVillage: "गांव का नाम दर्ज करें",
    villagePh: "गांव",
    next: "आगे →",
    submit: "आवेदन जमा करें",
    submitting: "जमा हो रहा है...",
    backToStep1: "← चरण 1 पर वापस",
    vehicleType: "वाहन का प्रकार",
    vehicleTypeReq: "वाहन का प्रकार *",
    selectVehicleType: "वाहन का प्रकार चुनें",
    canSelectMultiple: "आप एक या अधिक वाहन प्रकार चुन सकते हैं",
    vehicleNumberReq: "वाहन नंबर *",
    egVehicleNum: "उदा. MH01AB1234",
    drivingLicenseReq: "ड्राइविंग लाइसेंस नंबर *",
    egDl: "उदा. DL1234567890123",
    workDuration: "कार्य अवधि *",
    selectDuration: "अवधि चुनें",
    preferredLocation: "पसंदीदा स्थान *",
    egPreferredLoc: "उदा. हैदराबाद, वारंगल, गुंटूर",
    driverPreferences: "ड्राइवर प्राथमिकताएं",
    vehicleDetails: "वाहन विवरण",
    categoryReq: "श्रेणी *",
    selectCategory: "श्रेणी चुनें",
    single: "एकल",
    group: "समूह",
    workersCount: "मजदूरों की संख्या *",
    enterWorkers: "मजदूरों की संख्या दर्ज करें",
    skillsWorkType: "कौशल और कार्य प्रकार *",
    selectWorkTypes: "कार्य प्रकार चुनें...",
    selected: "चयनित",
    experienceReq: "अनुभव *",
    selectExperience: "अनुभव चुनें",
    exp01: "0–1 वर्ष",
    exp13: "1–3 वर्ष",
    exp35: "3–5 वर्ष",
    exp5: "5+ वर्ष",
    availabilityReq: "उपलब्धता *",
    fullTime: "पूर्णकालिक",
    partTime: "अंशकालिक",
    daily: "दैनिक",
    seasonal: "मौसमी",
    expectedWageLabel: "अपेक्षित वेतन",
    perDayShort: "/ प्रति दिन",
    perHourShort: "/ प्रति घंटा",
    perMonthShort: "/ प्रति माह",
    useCurrentLocation: "मेरे वर्तमान स्थान का उपयोग करें (अनुशंसित)",
    gettingLocation: "स्थान प्राप्त हो रहा है…",
    gpsCaptured: "GPS कैप्चर किया गया",
    gpsHelp: "किसानों को agrizin.com पर \"नज़दीकी\" खोज में आपको ढूंढने में मदद करता है",
    fillRequired: "कृपया सभी आवश्यक फ़ील्ड भरें",
    thankYou: "धन्यवाद!",
    thankYouBody: "Agrizin Partner चुनने के लिए धन्यवाद। आपका आवेदन सफलतापूर्वक जमा हो गया है। हमारी टीम सत्यापन के लिए जल्द ही आपसे संपर्क करेगी।",
    ok: "ठीक है",
    ...settingsAndHelpTranslations.hi,
  },
  te: {
    online: "ఆన్‌లైన్",
    offline: "ఆఫ్‌లైన్",
    notifications: "నోటిఫికేషన్లు",
    noNotifications: "కొత్త నోటిఫికేషన్లు లేవు",
    
    home: "హోమ్",
    categories: "వర్గాలు",
    earnings: "సంపాదన",
    account: "ఖాతా",
    
    goOnline: "ఆన్‌లైన్ అవ్వండి",
    goOffline: "ఆఫ్‌లైన్ అవ్వండి",
    loadingMap: "మ్యాప్ లోడ్ అవుతోంది...",
    completeAppToGoOnline: "దయచేసి లాగిన్ చేసి, ఆన్‌లైన్‌కు వెళ్ళడానికి మీ దరఖాస్తును పూర్తి చేయండి.",
    
    farmWorker: "వ్యవసాయ కూలీ",
    farmWorkerSub: "కూలీ పనులు కనుగొనండి",
    rentVehicle: "వాహనం అద్దె",
    rentVehicleSub: "కార్లు & బైక్‌లు అద్దెకు",
    agrizinDriver: "ఎగ్రిజిన్ డ్రైవర్",
    agrizinDriverSub: "వ్యవసాయ రవాణా",
    completed: "పూర్తయింది",
    inProgress: "ప్రగతిలో ఉంది",
    notAdded: "జోడించలేదు",
    
    myApplications: "📋 నా దరఖాస్తులు",
    editDetails: "వివరాలు మార్చండి",
    addFarmWorkerDetails: "వ్యవసాయ కూలీ వివరాలు జోడించండి",
    addRentVehicleDetails: "వాహనం అద్దె వివరాలు జోడించండి",
    addAgrizinDriverDetails: "ఎగ్రిజిన్ డ్రైవర్ వివరాలు జోడించండి",
    referPartner: "ఎగ్రిజిన్ పార్టనర్ రిఫర్ చేయండి",
    referSubtitle: "ఆహ్వానించి రివార్డ్‌లు పొందండి",
    appSettings: "యాప్ సెట్టింగ్‌లు",
    appSettingsSub: "భాష, నోటిఫికేషన్లు",
    logout: "లాగౌట్",
    welcomeAgrizin: "ఎగ్రిజిన్‌కు స్వాగతం",
    login: "లాగిన్",
    loginToView: "మీ సంపాదన చూడటానికి లాగిన్ అవ్వండి",
    name: "పేరు",
    enterName: "మీ పేరు నమోదు చేయండి",
    phoneNumber: "ఫోన్ నంబర్",
    otpSentTo: "OTP పంపబడింది",
    enterOtp: "OTP నమోదు చేయండి",
    enterOtpPlaceholder: "4-అంకెల OTP నమోదు చేయండి",
    verifyOtp: "OTP ధృవీకరించండి",
    verifying: "ధృవీకరిస్తోంది...",
    changeDetails: "← వివరాలు మార్చండి",
    back: "వెనుకకు",
    
    totalEarnings: "మొత్తం సంపాదన",
    thisWeek: "ఈ వారం",
    thisMonth: "ఈ నెల",
    dailyEarnings: "రోజువారీ సంపాదన",
    today: "ఈ రోజు:",
    trips: "ట్రిప్‌లు",
    paymentHistory: "చెల్లింపు చరిత్ర",
    getStartedEarnings: "మీ సంపాదనతో ప్రారంభించండి",
    getStartedEarningsDesc: "మీ సంపాదనను ఇక్కడ ట్రాక్ చేయడానికి సేవా నమోదును పూర్తి చేయండి.",
    availableBalance: "అందుబాటులో ఉన్న బ్యాలెన్స్",
    withdrawn: "విత్‌డ్రా చేయబడింది",
    pendingWithdrawalAmount: "పెండింగ్",
    withdrawMoney: "డబ్బు విత్‌డ్రా చేయండి",
    upiId: "UPI ID",
    amount: "మొత్తం",
    minimum: "కనీసం",
    confirmWithdrawal: "విత్‌డ్రాను నిర్ధారించండి",
    processing: "ప్రాసెస్ అవుతోంది...",
    withdrawalRequested: "విత్‌డ్రా అభ్యర్థన సమర్పించబడింది!",
    enterUpiId: "దయచేసి మీ UPI ID నమోదు చేయండి",
    minWithdrawal: "కనీస విత్‌డ్రా ₹50",
    insufficientBalance: "సరిపోని బ్యాలెన్స్",
    referralEarnings: "రిఫరల్ సంపాదన",
    totalReferrals: "మొత్తం రిఫరల్‌లు",
    noReferralsYet: "ఇంకా రిఫరల్‌లు లేవు. సంపాదించడానికి మీ కోడ్ షేర్ చేయండి!",
    noWithdrawalsYet: "ఇంకా విత్‌డ్రాలు లేవు",
    withdrawalHistory: "విత్‌డ్రా చరిత్ర",
    yourReferralCode: "మీ రిఫరల్ కోడ్",
    shareReferral: "రిఫరల్ షేర్ చేయండి",
    referralShareText: "Agrizin Partner యాప్‌లో చేరండి మరియు సంపాదించండి! నా రిఫరల్ కోడ్ ఉపయోగించండి:",
    copiedToClipboard: "కాపీ చేయబడింది!",
    perReferral: "రిఫరల్‌కు",
    
    nameLabel: "పేరు",
    skills: "నైపుణ్యాలు",
    experience: "అనుభవం",
    location: "ప్రదేశం",
    availability: "అందుబాటు",
    vehicle: "వాహనం",
    license: "లైసెన్స్",
    registration: "రిజిస్ట్రేషన్",
    years: "సంవత్సరాలు",
    
    submitted: "సమర్పించబడింది",
    
    selectLanguage: "భాష ఎంచుకోండి",
    english: "English",
    hindi: "हिन्दी",
    telugu: "తెలుగు",
    
    myEarnings: "నా సంపాదన",
    
    language: "భాష",
    notificationsToggle: "నోటిఫికేషన్లు",
    comingSoon: "త్వరలో వస్తుంది!",

    save: "మార్పులు సేవ్ చేయండి",
    saving: "సేవ్ అవుతోంది...",
    cancel: "రద్దు చేయండి",
    updateSuccess: "వివరాలు విజయవంతంగా అప్‌డేట్ చేయబడ్డాయి!",
    updateError: "అప్‌డేట్ విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.",
    state: "రాష్ట్రం",
    district: "జిల్లా",
    mandal: "మండలం",
    village: "గ్రామం",
    expectedWage: "ఆశించిన వేతనం",
    wageType: "వేతన రకం",
    perDay: "రోజుకు",
    perMonth: "నెలకు",
    perHour: "గంటకు",
    experienceYears: "అనుభవం (సంవత్సరాలు)",
    fullName: "పూర్తి పేరు",
    mobile: "మొబైల్",
    vehicleNumber: "వాహన నంబర్",
    vehicleUsageType: "వాహన ఉపయోగ రకం",
    drivingLicense: "డ్రైవింగ్ లైసెన్స్ నం.",
    vehicleMake: "వాహన తయారీ",
    vehicleModel: "వాహన మోడల్",
    registrationNo: "రిజిస్ట్రేషన్ నం.",

    loading: "లోడ్ అవుతోంది...",
    duplicateSubmission: "నకిలీ సమర్పణ",
    alreadySubmittedApp: "మీరు ఇప్పటికే మీ దరఖాస్తును సమర్పించారు.",
    alreadySubmittedDriver: "మీరు ఇప్పటికే ఎగ్రిజిన్ డ్రైవర్ దరఖాస్తును సమర్పించారు.",
    alreadyRegistered: "ఇప్పటికే నమోదు చేయబడింది",
    alreadyRegisteredFarm: "మీరు ఇప్పటికే వ్యవసాయ కూలీ దరఖాస్తును సమర్పించారు. మరొకటి సృష్టించలేరు.",
    goToDashboard: "డాష్‌బోర్డ్‌కు వెళ్ళండి",
    vehicleRegistration: "వాహన నమోదు",
    farmWorkerTitle: "వ్యవసాయ కూలీ",
    agrizinDriverTitle: "ఎగ్రిజిన్ డ్రైవర్",
    step1Personal: "దశ 1: వ్యక్తిగత వివరాలు",
    step2Vehicle: "దశ 2: వాహన వివరాలు",
    step2VehiclePref: "దశ 2: వాహనం & ప్రాధాన్యతలు",
    personalDetails: "వ్యక్తిగత వివరాలు",
    address: "చిరునామా",
    addressDetails: "చిరునామా వివరాలు",
    upload: "అప్‌లోడ్",
    change: "మార్చండి",
    uploadImage: "చిత్రాన్ని అప్‌లోడ్ చేయండి",
    uploadRcImage: "RC చిత్రాన్ని అప్‌లోడ్ చేయండి",
    uploadRcOptional: "RC డాక్యుమెంట్ అప్‌లోడ్ చేయండి (ఐచ్ఛికం)",
    uploadVehiclePhotos: "వాహన ఫోటోలు అప్‌లోడ్ చేయండి",
    uploadDrivingLicense: "డ్రైవింగ్ లైసెన్స్ అప్‌లోడ్ చేయండి",
    uploadAadhaarPan: "ఆధార్ / పాన్ చిత్రాలు *",
    frontSide: "ముందు వైపు",
    backSide: "వెనుక వైపు",
    frontImage: "ముందు చిత్రం",
    backImage: "వెనుక చిత్రం",
    addPhoto: "ఫోటో జోడించండి",
    nameRequired: "పూర్తి పేరు *",
    egJohn: "ఉదా. రాజేష్ కుమార్",
    age: "వయస్సు",
    eg25: "ఉదా. 25",
    gender: "లింగం",
    selectGender: "లింగం ఎంచుకోండి",
    male: "పురుషుడు",
    female: "స్త్రీ",
    other: "ఇతర",
    mobileRequired: "మొబైల్ నంబర్ *",
    egMobile: "ఉదా. 9876543210",
    aadhaarPanLabel: "ఆధార్ / పాన్ నంబర్ *",
    egAadhaar: "ఉదా. 123456789012 లేదా ABCDE1234F",
    country: "దేశం",
    india: "భారతదేశం",
    selectStateReq: "రాష్ట్రం ఎంచుకోండి *",
    districtReq: "జిల్లా *",
    selectMandal: "మండలం",
    enterVillage: "గ్రామం పేరు నమోదు చేయండి",
    villagePh: "గ్రామం",
    next: "తర్వాత →",
    submit: "దరఖాస్తు సమర్పించండి",
    submitting: "సమర్పిస్తోంది...",
    backToStep1: "← దశ 1కు తిరిగి",
    vehicleType: "వాహనం రకం",
    vehicleTypeReq: "వాహనం రకం *",
    selectVehicleType: "వాహనం రకం ఎంచుకోండి",
    canSelectMultiple: "మీరు ఒకటి లేదా అంతకంటే ఎక్కువ వాహన రకాలను ఎంచుకోవచ్చు",
    vehicleNumberReq: "వాహన నంబర్ *",
    egVehicleNum: "ఉదా. TS01AB1234",
    drivingLicenseReq: "డ్రైవింగ్ లైసెన్స్ నంబర్ *",
    egDl: "ఉదా. DL1234567890123",
    workDuration: "పని వ్యవధి *",
    selectDuration: "వ్యవధి ఎంచుకోండి",
    preferredLocation: "ప్రాధాన్య ప్రదేశం *",
    egPreferredLoc: "ఉదా. హైదరాబాద్, వరంగల్, గుంటూరు",
    driverPreferences: "డ్రైవర్ ప్రాధాన్యతలు",
    vehicleDetails: "వాహన వివరాలు",
    categoryReq: "వర్గం *",
    selectCategory: "వర్గం ఎంచుకోండి",
    single: "ఒంటరి",
    group: "సమూహం",
    workersCount: "కూలీల సంఖ్య *",
    enterWorkers: "కూలీల సంఖ్యను నమోదు చేయండి",
    skillsWorkType: "నైపుణ్యాలు & పని రకం *",
    selectWorkTypes: "పని రకాలను ఎంచుకోండి...",
    selected: "ఎంచుకోబడింది",
    experienceReq: "అనుభవం *",
    selectExperience: "అనుభవం ఎంచుకోండి",
    exp01: "0–1 సంవత్సరాలు",
    exp13: "1–3 సంవత్సరాలు",
    exp35: "3–5 సంవత్సరాలు",
    exp5: "5+ సంవత్సరాలు",
    availabilityReq: "అందుబాటు *",
    fullTime: "పూర్తి సమయం",
    partTime: "పార్ట్-టైమ్",
    daily: "రోజువారీ",
    seasonal: "సీజనల్",
    expectedWageLabel: "ఆశించిన వేతనం",
    perDayShort: "/ రోజుకు",
    perHourShort: "/ గంటకు",
    perMonthShort: "/ నెలకు",
    useCurrentLocation: "నా ప్రస్తుత స్థానాన్ని ఉపయోగించండి (సిఫార్సు)",
    gettingLocation: "స్థానం పొందుతోంది…",
    gpsCaptured: "GPS క్యాప్చర్ చేయబడింది",
    gpsHelp: "agrizin.com లో \"సమీపంలో\" శోధనలో రైతులకు మిమ్మల్ని కనుగొనడంలో సహాయపడుతుంది",
    fillRequired: "దయచేసి అన్ని అవసరమైన ఫీల్డ్‌లను పూరించండి",
    thankYou: "ధన్యవాదాలు!",
    thankYouBody: "Agrizin Partner ఎంచుకున్నందుకు ధన్యవాదాలు. మీ దరఖాస్తు విజయవంతంగా సమర్పించబడింది. మా బృందం ధృవీకరణ కోసం త్వరలో మిమ్మల్ని సంప్రదిస్తుంది.",
    ok: "సరే",
    ...settingsAndHelpTranslations.te,
  },
} as const;

type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("agrizin_lang");
    return (saved as Language) || "en";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("agrizin_lang", lang);
  };

  const t = (key: TranslationKey): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
